networks:
  suisse:
    driver: bridge

volumes:
  postgres-suisse-data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:


services:
  postgres-suisse:
    image: postgres:15-alpine
    container_name: postgres-suisse
    environment:
      POSTGRES_DB: oms_suisse
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres-suisse-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - suisse
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 30s
      timeout: 10s
      retries: 3

  backend-suisse-1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-suisse-1
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres-suisse:5432/oms_suisse
      KEY: ${JWT_SECRET}
      JWT_EXPIRES: ${JWT_EXPIRES}
      API_IA_URL: ${API_IA_URL_CH}
      PORT: ${PORT_BACKEND_CH}
      GDPR_MODE: ${GDPR_MODE_CH}
      LOCALE: ${LOCALE_CH}
    depends_on:
      postgres-suisse:
        condition: service_healthy
    networks:
      - suisse
    restart: unless-stopped

  backend-suisse-2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-suisse-2
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres-suisse:5432/oms_suisse
      KEY: ${JWT_SECRET}
      JWT_EXPIRES: ${JWT_EXPIRES}
      API_IA_URL: ${API_IA_URL_CH}
      PORT: ${PORT_BACKEND_CH}
      GDPR_MODE: ${GDPR_MODE_CH}
      LOCALE: ${LOCALE_CH}
    depends_on:
      postgres-suisse:
        condition: service_healthy
    networks:
      - suisse
    restart: unless-stopped

  api-ia-suisse:
    build:
      context: ./ml_api
      dockerfile: Dockerfile
    container_name: api-ia-suisse
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres-suisse:5432/oms_suisse
      PYTHONUNBUFFERED: 1
      GDPR_MODE: true
    ports:
      - "8004:8000"
    depends_on:
      postgres-suisse:
        condition: service_healthy
    networks:
      - suisse
    restart: unless-stopped

  frontend-suisse-1:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: ${VITE_API_URL_CH}
      VITE_COUNTRY: ${VITE_COUNTRY_CH}
      VITE_LOCALE: ${VITE_LOCALE_CH}
      VITE_GDPR_MODE: ${VITE_GDPR_MODE_CH}
      VITE_MULTI_LANG: ${VITE_MULTI_LANG_CH}
    container_name: frontend-suisse-1
    networks:
      - suisse
    restart: unless-stopped

  frontend-suisse-2:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: ${VITE_API_URL_CH}
      VITE_COUNTRY: ${VITE_COUNTRY_CH}
      VITE_LOCALE: ${VITE_LOCALE_CH}
      VITE_GDPR_MODE: ${VITE_GDPR_MODE_CH}
      VITE_MULTI_LANG: ${VITE_MULTI_LANG_CH}
    container_name: frontend-suisse-2
    networks:
      - suisse
    restart: unless-stopped

  etl-suisse:
    build:
      context: .
      dockerfile: ./csv_to_postgres/Dockerfile
    container_name: etl-suisse
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres-suisse:5432/oms_suisse
      PYTHONUNBUFFERED: 1
      GDPR_MODE: true
      CSV_FILE_PATH: ${CSV_FILE_PATH}
    depends_on:
      postgres-suisse:
        condition: service_healthy
    networks:
      - suisse
    restart: unless-stopped

  nginx-suisse:
    image: nginx:alpine
    container_name: nginx-suisse
    ports:
      - "3004:3004"
    depends_on:
      - backend-suisse-1
      - backend-suisse-2
      - frontend-suisse-1
      - frontend-suisse-2
    networks:
      - suisse
    volumes:
      - ./nginx-suisse.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  cadvisor-suisse:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8084:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/snap/docker/common/var-lib-docker:/var/lib/docker:ro
    restart: unless-stopped