name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:

  tests:
    if: github.ref == 'refs/heads/develop' || github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install wait-on
        run: npm install -g wait-on
      
      - name: Lint frontend
        run: npx eslint frontend/src/ --format html -o reports/frontend/lint.html

      - name: Upload lint reports frontend
        uses: actions/upload-artifact@v3
        with:
          name: frontend-lint-report
          path: reports/frontend/lint.html

      - name: Lint backend Apollo
        run: npx eslint backend/src/ --format html -o reports/backend/lint.html

      - name: Upload lint reports backend Apollo
        uses: actions/upload-artifact@v3
        with:
          name: backend-apollo-lint-report
          path: reports/backend/lint.html

      - name: Lint API IA
        run: |
          python3 -m pip install flake8 flake8-html
          flake8 app.py config.py generate_benchmark_report.py model_comparison.py predict.py train_all_models.py --format=html --htmldir=reports/ml_api
        working-directory: ./ml_api

      - name: Upload lint reports API IA
        uses: actions/upload-artifact@v3
        with:
          name: ml-api-lint-report
          path: reports/ml_api/

      - name: Start France stack
        run: docker compose -f docker-compose.fr.yml up -d

      - name: Start USA stack
        run: docker compose -f docker-compose.usa.yml up -d

      - name: Start Suisse stack
        run: docker compose -f docker-compose.ch.yml up -d

      - name: Install Cypress dependencies
        run: npm ci
        working-directory: ./cypress

      - name: Run Cypress tests USA
        run: |
          mkdir -p reports/frontend/cypress/usa
          npx cypress run --config-file cypress.config.js 
            --reporter mocha-multi-reporters --reporter-options configFile=reporter-config.json
        working-directory: ./cypress
        env:
          CYPRESS_BASE_URL: http://localhost:3000

      - name: Run Cypress tests France
        run: |
          mkdir -p reports/frontend/cypress/france
          npx cypress run --config-file cypress.config.js 
            --reporter mocha-multi-reporters --reporter-options configFile=reporter-config.json
        working-directory: ./cypress
        env:
          CYPRESS_BASE_URL: http://localhost:3002

      - name: Run Cypress tests Suisse
        run: |
          mkdir -p reports/frontend/cypress/suisse
          npx cypress run --config-file cypress.config.js 
            --reporter mocha-multi-reporters --reporter-options configFile=reporter-config.json
        working-directory: ./cypress
        env:
          CYPRESS_BASE_URL: http://localhost:3004

      - name: Upload Cypress reports
        uses: actions/upload-artifact@v3
        with:
          name: frontend-cypress-reports
          path: reports/frontend/cypress/

  build-and-push:
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}          
      - run: |
          REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')

          # Backend
          docker build -t ghcr.io/${REPO_LC}/backend-suisse:latest -f backend/Dockerfile ./backend
          docker push ghcr.io/${REPO_LC}/backend-suisse:latest

          # API IA
          docker build -t ghcr.io/${REPO_LC}/api-ia-suisse:latest -f ml_api/Dockerfile ./ml_api
          docker push ghcr.io/${REPO_LC}/api-ia-suisse:latest

          # Frontend
          docker build -t ghcr.io/${REPO_LC}/frontend-suisse:latest \
            --build-arg VITE_API_URL=${VITE_API_URL_CH} \
            --build-arg VITE_COUNTRY=${VITE_COUNTRY_CH} \
            --build-arg VITE_LOCALE=${VITE_LOCALE_CH} \
            --build-arg VITE_GDPR_MODE=${VITE_GDPR_MODE_CH} \
            --build-arg VITE_MULTI_LANG=${VITE_MULTI_LANG_CH} \
            -f frontend/Dockerfile ./frontend
          docker push ghcr.io/${REPO_LC}/frontend-suisse:latest

          # ETL
          docker build -t ghcr.io/${REPO_LC}/etl-suisse:latest -f csv_to_postgres/Dockerfile .
          docker push ghcr.io/${REPO_LC}/etl-suisse:latest